name: eShopOnWeb Build and Test

on: workflow_dispatch

env:
  RESOURCE_GROUP: rg-eshoponweb-sea
  LOCATION: southeastasia
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: 9b90c475-17f1-473d-a8bc-2f35310d2913
  WEBAPP_NAME: devops-webapp-sea-2039522343

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'

      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{ env.DOTNET_ROOT }}/myapp
          cd ${{ env.DOTNET_ROOT }}/myapp
          zip -r ../app.zip .

      - name: Upload artifact (app)
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/app.zip

      - name: Upload artifact (bicep)
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE_FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: Development
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact (app)
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .net-app

      - name: Download artifact (bicep)
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: bicep-template

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Ensure RG exists (or let arm-deploy create it by also passing region)
      - name: Ensure resource group
        run: az group create -n "${{ env.RESOURCE_GROUP }}" -l "${{ env.LOCATION }}"

      - name: Deploy Bicep
        uses: azure/arm-deploy@v2
        with:
          scope: resourceGroup
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          region: ${{ env.LOCATION }}             # needed if RG creation is required
          deploymentName: eshoponweb
          template: bicep-template/webapp.bicep
          parameters: >
            location=${{ env.LOCATION }}
            webAppName=${{ env.WEBAPP_NAME }}
            sku=S1
          failOnStdErr: false

      - name: Publish Website to WebApp
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy \
              --name "${{ env.WEBAPP_NAME }}" \
              --resource-group "${{ env.RESOURCE_GROUP }}" \
              --src-path .net-app/app.zip \
              --type zip
